project:
  type: website

website:
  title: ""
  site-url: "https://garden.caruthe.rs"
  repo-url: https://github.com/kelly-sovacool/garden.caruthe.rs
  open-graph: true
  navbar:
    left:
    - text: About
      href: index.qmd
    - href: plants.qmd
    - href: resources.qmd
  page-footer: |
    © 2026 Kelly & David


format:
  html:
    theme:
      light:
        - yeti
        - styles.scss
    toc: false
    title-block-banner: true
