

## Planning

### Choose your site

anywhere in your yard! small space, large space, even a tiny garden dedicated
to native plants makes an impact!


link to design your wild webinar on garden layouts

### Choose your plants

mix of flowering plants and grasses.

make sure they're native to your region

prioritize plants favored by a range of species: birds + pollinators; throughout lifecycle - food for adults and food for larvae

range of bloom times from spring through fall

choose plants that prefer your site: full sun to shade, dry to moist soil.

### Choose your growing method

prefer local ecotype if possible

two routes: buy nursery plants or grow from seed yourself

winter sowing is a very easy way to grow from seed

can also direct sow

### Sketch a rough plan

12" spacing between plants

clusters of 3-5 plants of the same species (odd numbers usually "look" better)

repeat drifts

shorter plants near walkways

grasses help support taller plants

## Site preparation

smothering grass. use sod cutter, or cut as low as possible then cover with cardboard

edging

mulching

## Planting

## Maintenance

pulling weeds, watering deeply but infrequently

no pesticides! don't harm the creatures you're trying to feed